# cars_data.py
# ------------------------------------------------------------
# Yahan DWON Cars ki saari gaadiyon ki list hai.
# Nayi gaadi add karni ho toh bas ek naya { ... } block copy karke
# neeche list mein daal do aur uski details badal do.
#
# segment ke 4 options hain:
#   "modified"  -> Brabus wali modified cars (sabse zyada focus)
#   "sports"    -> Sports / AMG cars
#   "suv"       -> SUV
#   "sedan"     -> Sedan
#
# price_aed = ek din (24 ghante) ka kiraya, UAE Dirham mein.
# Kiraye humne apne hisaab se rakhe hain, zaroorat ho toh badal lo.
# Specs internet se li gayi hain (Brabus / Mercedes official data).
# ------------------------------------------------------------

CARS = [
    # ==================== MODIFIED (BRABUS) ====================
    {
        "id": "brabus-800-superblack",
        "name": "BRABUS 800 SUPERBLACK",
        "base": "Mercedes-AMG G 63 (W465)",
        "segment": "modified",
        "image": "b800g.jpg",
        "engine": "4.0L V8 Biturbo (BRABUS turbochargers)",
        "power_hp": 800,
        "torque_nm": 1000,
        "zero_100": 4.0,
        "top_speed": 240,
        "transmission": "9-speed automatic",
        "drive": "All-wheel drive",
        "seats": 5,
        "price_aed": 5500,
        "tag": "",
        "about": "The newest G-Class turned stealth monster: all black, carbon everywhere and 800 hp.",
    },
    {
        "id": "brabus-900-rocket-edition",
        "name": "BRABUS 900 ROCKET EDITION",
        "base": "Mercedes-AMG G 63 (W463A)",
        "segment": "modified",
        "image": "b900g.jpg",
        "engine": "4.5L V8 Biturbo (bored-out Rocket engine)",
        "power_hp": 900,
        "torque_nm": 1050,
        "zero_100": 3.7,
        "top_speed": 280,
        "transmission": "9-speed automatic",
        "drive": "All-wheel drive",
        "seats": 5,
        "price_aed": 7500,
        "tag": "1 of 25",
        "about": "The top of the BRABUS G-Class range. Billet crankshaft, forged rods and 900 hp.",
    },
    {
        "id": "brabus-800-widestar",
        "name": "BRABUS 800 WIDESTAR",
        "base": "Mercedes-AMG G 63 (W463A)",
        "segment": "modified",
        "image": "b800g_alt.jpg",
        "engine": "4.0L V8 Biturbo (BRABUS turbochargers)",
        "power_hp": 800,
        "torque_nm": 1000,
        "zero_100": 3.9,
        "top_speed": 240,
        "transmission": "9-speed automatic",
        "drive": "All-wheel drive",
        "seats": 5,
        "price_aed": 5000,
        "tag": "",
        "about": "Wide-body G 63 with extra-wide arches, big forged wheels and a loud sports exhaust.",
    },
    {
        "id": "brabus-xlp-900-6x6",
        "name": "BRABUS XLP 900 6x6 SUPERBLACK",
        "base": "Mercedes-AMG G 63 pickup (6 wheels)",
        "segment": "modified",
        "image": "bxlp900.jpg",
        "engine": "4.5L V8 Biturbo (Rocket 900 engine)",
        "power_hp": 900,
        "torque_nm": 1250,
        "zero_100": 5.2,
        "top_speed": 210,
        "transmission": "9-speed automatic",
        "drive": "Six-wheel drive",
        "seats": 4,
        "price_aed": 12000,
        "tag": "Desert King",
        "about": "Six wheels, portal axles and 900 hp. Built for the dunes, looks good at the mall too.",
    },
    {
        "id": "brabus-xlp-800-6x6",
        "name": "BRABUS XLP 800 6x6 ADVENTURE",
        "base": "Mercedes-AMG G 63 pickup (6 wheels)",
        "segment": "modified",
        "image": "bxlp800.jpg",
        "engine": "4.0L V8 Biturbo",
        "power_hp": 800,
        "torque_nm": 1000,
        "zero_100": 5.8,
        "top_speed": 210,
        "transmission": "9-speed automatic",
        "drive": "Six-wheel drive",
        "seats": 4,
        "price_aed": 10000,
        "tag": "",
        "about": "The adventure pickup: six-wheel drive, huge off-road tyres and a luxury cabin.",
    },
    {
        "id": "brabus-900-superblack-gls",
        "name": "BRABUS 900 SUPERBLACK",
        "base": "Mercedes-AMG GLS 63 4MATIC+",
        "segment": "modified",
        "image": "b900gls.jpg",
        "engine": "4.5L V8 Biturbo (Rocket 900 engine)",
        "power_hp": 900,
        "torque_nm": 1050,
        "zero_100": 3.6,
        "top_speed": 330,
        "transmission": "9-speed automatic",
        "drive": "All-wheel drive",
        "seats": 7,
        "price_aed": 6500,
        "tag": "330 km/h SUV",
        "about": "A 7-seat family SUV that reaches 330 km/h. The fastest seven-seater we have.",
    },
    {
        "id": "brabus-800-gls",
        "name": "BRABUS 800",
        "base": "Mercedes-AMG GLS 63 4MATIC+",
        "segment": "modified",
        "image": "b800gls.jpg",
        "engine": "4.0L V8 Biturbo (PowerXtra B40S-800)",
        "power_hp": 800,
        "torque_nm": 1000,
        "zero_100": 3.8,
        "top_speed": 280,
        "transmission": "9-speed automatic",
        "drive": "All-wheel drive",
        "seats": 7,
        "price_aed": 4500,
        "tag": "",
        "about": "Luxury 7-seater with 24-inch forged wheels, lowered suspension and 800 hp.",
    },
    {
        "id": "brabus-800-gle-coupe",
        "name": "BRABUS 800 COUPE",
        "base": "Mercedes-AMG GLE 63 S Coupé",
        "segment": "modified",
        "image": "b800gle.jpg",
        "engine": "4.0L V8 Biturbo (PowerXtra B40S-800)",
        "power_hp": 800,
        "torque_nm": 1000,
        "zero_100": 3.4,
        "top_speed": 280,
        "transmission": "9-speed automatic",
        "drive": "All-wheel drive",
        "seats": 5,
        "price_aed": 4000,
        "tag": "",
        "about": "Sporty coupé-SUV that's faster than most sports cars off the line.",
    },
    {
        "id": "brabus-930",
        "name": "BRABUS 930",
        "base": "Mercedes-AMG S 63 E PERFORMANCE",
        "segment": "modified",
        "image": "b930.jpg",
        "engine": "4.0L V8 Biturbo + electric motor (hybrid)",
        "power_hp": 930,
        "torque_nm": 1510,
        "zero_100": 3.2,
        "top_speed": 290,
        "transmission": "9-speed automatic",
        "drive": "All-wheel drive",
        "seats": 5,
        "price_aed": 6000,
        "tag": "Hybrid",
        "about": "Luxury limo with 930 hp. Silent in 'Coming Home' mode, loud V8 in 'Sport'.",
    },
    {
        "id": "brabus-850-maybach",
        "name": "BRABUS 850",
        "base": "Mercedes-Maybach S 680",
        "segment": "modified",
        "image": "b850.jpg",
        "engine": "6.3L V12 Biturbo (increased displacement)",
        "power_hp": 850,
        "torque_nm": 1400,
        "zero_100": 4.1,
        "top_speed": 250,
        "transmission": "9-speed automatic",
        "drive": "All-wheel drive",
        "seats": 4,
        "price_aed": 7000,
        "tag": "V12",
        "about": "The ultimate chauffeur car. V12 power, champagne seats and total silence.",
    },
    {
        "id": "brabus-900-maybach",
        "name": "BRABUS 900",
        "base": "Mercedes-Maybach S 650",
        "segment": "modified",
        "image": "b900m.jpg",
        "engine": "6.3L V12 Biturbo",
        "power_hp": 900,
        "torque_nm": 1500,
        "zero_100": 3.7,
        "top_speed": 350,
        "transmission": "7-speed automatic",
        "drive": "Rear-wheel drive",
        "seats": 4,
        "price_aed": 6500,
        "tag": "V12",
        "about": "Classic BRABUS Maybach with a 900 hp V12. A true collector's limousine.",
    },
    {
        "id": "brabus-800-e63",
        "name": "BRABUS 800",
        "base": "Mercedes-AMG E 63 S 4MATIC+",
        "segment": "modified",
        "image": "b800e.jpg",
        "engine": "4.0L V8 Biturbo (PowerXtra B40S-800)",
        "power_hp": 800,
        "torque_nm": 1000,
        "zero_100": 3.0,
        "top_speed": 300,
        "transmission": "9-speed automatic",
        "drive": "All-wheel drive",
        "seats": 5,
        "price_aed": 3500,
        "tag": "Best value",
        "about": "Everyday executive car on the outside, 800 hp and 300 km/h underneath.",
    },
    {
        "id": "brabus-1000-gt",
        "name": "BRABUS 1000",
        "base": "Mercedes-AMG GT 63 S E PERFORMANCE Coupé",
        "segment": "modified",
        "image": "b1000gt.jpg",
        "engine": "4.5L V8 Biturbo + electric motor (hybrid)",
        "power_hp": 1000,
        "torque_nm": 1620,
        "zero_100": 2.6,
        "top_speed": 316,
        "transmission": "9-speed automatic",
        "drive": "All-wheel drive",
        "seats": 4,
        "price_aed": 9500,
        "tag": "1000 HP",
        "about": "The most powerful car in our fleet. 0 to 100 km/h in 2.6 seconds.",
    },
    {
        "id": "brabus-750-gt",
        "name": "BRABUS 750",
        "base": "Mercedes-AMG GT 63 Coupé",
        "segment": "modified",
        "image": "b750gt.jpg",
        "engine": "4.0L V8 Biturbo (PowerXtra B40S-750)",
        "power_hp": 750,
        "torque_nm": 900,
        "zero_100": 2.9,
        "top_speed": 315,
        "transmission": "9-speed automatic",
        "drive": "All-wheel drive",
        "seats": 4,
        "price_aed": 5000,
        "tag": "",
        "about": "Carbon aero kit, 21/22-inch Monoblock Z wheels and a sports exhaust.",
    },
    {
        "id": "brabus-750-sl",
        "name": "BRABUS 750 BODO BUSCHMANN EDITION",
        "base": "Mercedes-AMG SL 63 4MATIC+",
        "segment": "modified",
        "image": "b750sl.jpg",
        "engine": "4.0L V8 Biturbo (BRABUS turbochargers)",
        "power_hp": 750,
        "torque_nm": 900,
        "zero_100": 3.3,
        "top_speed": 315,
        "transmission": "9-speed automatic",
        "drive": "All-wheel drive",
        "seats": 4,
        "price_aed": 6000,
        "tag": "1 of 25",
        "about": "Open-top BRABUS roadster made in honour of the company's founder.",
    },

    # ==================== SPORTS ====================
    {
        "id": "amg-gt-63-s-e",
        "name": "Mercedes-AMG GT 63 S E PERFORMANCE",
        "base": "Coupé (C192)",
        "segment": "sports",
        "image": "gt63se.jpg",
        "engine": "4.0L V8 Biturbo + electric motor",
        "power_hp": 816,
        "torque_nm": 1420,
        "zero_100": 2.8,
        "top_speed": 320,
        "transmission": "AMG 9-speed MCT",
        "drive": "All-wheel drive",
        "seats": 4,
        "price_aed": 3500,
        "tag": "",
        "about": "AMG's most powerful GT. Hybrid V8 with an electric boost.",
    },
    {
        "id": "amg-gt-63",
        "name": "Mercedes-AMG GT 63 4MATIC+",
        "base": "Coupé (C192)",
        "segment": "sports",
        "image": "gt63.jpg",
        "engine": "4.0L V8 Biturbo",
        "power_hp": 585,
        "torque_nm": 800,
        "zero_100": 3.2,
        "top_speed": 315,
        "transmission": "AMG 9-speed MCT",
        "drive": "All-wheel drive",
        "seats": 4,
        "price_aed": 2800,
        "tag": "",
        "about": "Hand-built V8 sports coupé with 2+2 seats.",
    },
    {
        "id": "amg-sl-63",
        "name": "Mercedes-AMG SL 63 4MATIC+",
        "base": "Roadster (R232)",
        "segment": "sports",
        "image": "sl63.jpg",
        "engine": "4.0L V8 Biturbo",
        "power_hp": 585,
        "torque_nm": 800,
        "zero_100": 3.6,
        "top_speed": 315,
        "transmission": "AMG 9-speed MCT",
        "drive": "All-wheel drive",
        "seats": 4,
        "price_aed": 2500,
        "tag": "Convertible",
        "about": "Soft-top roadster, perfect for a Jumeirah Beach Road evening drive.",
    },
    {
        "id": "amg-c-63-s-e",
        "name": "Mercedes-AMG C 63 S E PERFORMANCE",
        "base": "Sedan (W206)",
        "segment": "sports",
        "image": "c63.jpg",
        "engine": "2.0L 4-cyl Turbo + electric motor",
        "power_hp": 680,
        "torque_nm": 1020,
        "zero_100": 3.4,
        "top_speed": 280,
        "transmission": "AMG 9-speed MCT",
        "drive": "All-wheel drive",
        "seats": 5,
        "price_aed": 1800,
        "tag": "",
        "about": "Compact sports sedan with Formula 1 hybrid tech and 680 hp.",
    },

    # ==================== SUV ====================
    {
        "id": "amg-g-63",
        "name": "Mercedes-AMG G 63",
        "base": "G-Class (W465)",
        "segment": "suv",
        "image": "g63.jpg",
        "engine": "4.0L V8 Biturbo (mild hybrid)",
        "power_hp": 585,
        "torque_nm": 850,
        "zero_100": 4.4,
        "top_speed": 220,
        "transmission": "AMG 9-speed automatic",
        "drive": "All-wheel drive",
        "seats": 5,
        "price_aed": 2800,
        "tag": "Most booked",
        "about": "Dubai's favourite SUV. Iconic boxy look, V8 sound and serious off-road ability.",
    },
    {
        "id": "gls-580",
        "name": "Mercedes-Benz GLS 580 4MATIC",
        "base": "GLS (X167)",
        "segment": "suv",
        "image": "gls.jpg",
        "engine": "4.0L V8 Biturbo (EQ Boost)",
        "power_hp": 510,
        "torque_nm": 700,
        "zero_100": 4.7,
        "top_speed": 250,
        "transmission": "9G-TRONIC",
        "drive": "All-wheel drive",
        "seats": 7,
        "price_aed": 1400,
        "tag": "7 seats",
        "about": "The S-Class of SUVs. Big, quiet and very comfortable for 7 people.",
    },
    {
        "id": "gle-450",
        "name": "Mercedes-Benz GLE 450 4MATIC",
        "base": "GLE (W167)",
        "segment": "suv",
        "image": "gle.jpg",
        "engine": "3.0L 6-cyl Turbo (EQ Boost)",
        "power_hp": 381,
        "torque_nm": 500,
        "zero_100": 5.6,
        "top_speed": 250,
        "transmission": "9G-TRONIC",
        "drive": "All-wheel drive",
        "seats": 7,
        "price_aed": 950,
        "tag": "",
        "about": "Smooth six-cylinder family SUV with plenty of space.",
    },
    {
        "id": "glc-300",
        "name": "Mercedes-Benz GLC 300 4MATIC",
        "base": "GLC (X254)",
        "segment": "suv",
        "image": "glc.jpg",
        "engine": "2.0L 4-cyl Turbo (mild hybrid)",
        "power_hp": 258,
        "torque_nm": 400,
        "zero_100": 6.2,
        "top_speed": 240,
        "transmission": "9G-TRONIC",
        "drive": "All-wheel drive",
        "seats": 5,
        "price_aed": 650,
        "tag": "",
        "about": "The perfect everyday luxury SUV for the city.",
    },
    {
        "id": "gla-250",
        "name": "Mercedes-Benz GLA 250",
        "base": "GLA (H247)",
        "segment": "suv",
        "image": "gla.jpg",
        "engine": "2.0L 4-cyl Turbo",
        "power_hp": 224,
        "torque_nm": 350,
        "zero_100": 6.7,
        "top_speed": 240,
        "transmission": "8G-DCT",
        "drive": "All-wheel drive",
        "seats": 5,
        "price_aed": 400,
        "tag": "Budget",
        "about": "Compact, easy to park and light on fuel. Our most affordable SUV.",
    },

    # ==================== SEDAN ====================
    {
        "id": "maybach-s-680",
        "name": "Mercedes-Maybach S 680",
        "base": "S-Class Maybach (Z223)",
        "segment": "sedan",
        "image": "maybach.jpg",
        "engine": "6.0L V12 Biturbo",
        "power_hp": 612,
        "torque_nm": 900,
        "zero_100": 4.5,
        "top_speed": 250,
        "transmission": "9G-TRONIC",
        "drive": "All-wheel drive",
        "seats": 4,
        "price_aed": 3500,
        "tag": "Chauffeur",
        "about": "Two-tone luxury limousine with reclining rear seats. Best with a chauffeur.",
    },
    {
        "id": "s-580",
        "name": "Mercedes-Benz S 580 4MATIC",
        "base": "S-Class (W223)",
        "segment": "sedan",
        "image": "s580.jpg",
        "engine": "4.0L V8 Biturbo (EQ Boost)",
        "power_hp": 503,
        "torque_nm": 700,
        "zero_100": 4.4,
        "top_speed": 250,
        "transmission": "9G-TRONIC",
        "drive": "All-wheel drive",
        "seats": 5,
        "price_aed": 1800,
        "tag": "",
        "about": "The flagship Mercedes sedan. Business meetings, weddings, VIP guests.",
    },
    {
        "id": "e-300",
        "name": "Mercedes-Benz E 300",
        "base": "E-Class (W214)",
        "segment": "sedan",
        "image": "e300.jpg",
        "engine": "2.0L 4-cyl Turbo (mild hybrid)",
        "power_hp": 258,
        "torque_nm": 400,
        "zero_100": 6.2,
        "top_speed": 250,
        "transmission": "9G-TRONIC",
        "drive": "Rear-wheel drive",
        "seats": 5,
        "price_aed": 550,
        "tag": "",
        "about": "Business-class comfort with the latest MBUX screens.",
    },
    {
        "id": "c-200",
        "name": "Mercedes-Benz C 200",
        "base": "C-Class (W206)",
        "segment": "sedan",
        "image": "c200.jpg",
        "engine": "1.5L 4-cyl Turbo (EQ Boost)",
        "power_hp": 204,
        "torque_nm": 300,
        "zero_100": 7.3,
        "top_speed": 246,
        "transmission": "9G-TRONIC",
        "drive": "Rear-wheel drive",
        "seats": 5,
        "price_aed": 350,
        "tag": "Budget",
        "about": "Stylish, economical and easy to drive. Great for everyday use in Dubai.",
    },
]


# Har segment ka naam aur chhota description (website pe dikhane ke liye)
SEGMENTS = {
    "modified": {
        "title": "BRABUS Modified",
        "subtitle": "Mercedes cars hand-tuned by BRABUS in Germany. 750 to 1000 hp.",
        "icon": "local_fire_department",
    },
    "sports": {
        "title": "Sports Cars",
        "subtitle": "Mercedes-AMG performance coupés, roadsters and sedans.",
        "icon": "speed",
    },
    "suv": {
        "title": "SUVs",
        "subtitle": "From the compact GLA to the legendary G 63.",
        "icon": "directions_car",
    },
    "sedan": {
        "title": "Sedans",
        "subtitle": "C-Class to Maybach. Comfort for every trip.",
        "icon": "airline_seat_recline_extra",
    },
}


def get_car(car_id):
    """ID se ek gaadi dhoondh ke deta hai. Na mile toh None."""
    for car in CARS:
        if car["id"] == car_id:
            return car
    return None


def cars_in_segment(segment):
    """Ek segment ki saari gaadiyan deta hai."""
    return [car for car in CARS if car["segment"] == segment]
